# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 16:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.IntegerField()),
                ('bid_time', models.DateTimeField(default=datetime.datetime.now)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapapp.Ads')),
            ],
        ),
        migrations.CreateModel(
            name='Bid_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('bidder_name', models.CharField(default='', max_length=30)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scrapapp.Ads')),
                ('bid_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scrapapp.Bid')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('baseprice', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dealer', models.BooleanField(default=False)),
                ('is_seller', models.BooleanField(default=True)),
                ('ph_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('reg_image', models.ImageField(upload_to='')),
                ('landmark', models.CharField(max_length=30)),
                ('reg_id', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bid_detail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapapp.Product'),
        ),
        migrations.AddField(
            model_name='bid_detail',
            name='seller_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='ads',
            name='pname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapapp.Product'),
        ),
        migrations.AddField(
            model_name='ads',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapapp.UserProfile'),
        ),
    ]
