# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapapp.UserProfile'),
        ),
        migrations.AlterField(
            model_name='bid_detail',
            name='bidder_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bid_detail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapapp.Product'),
        ),
    ]
