# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0004_auto_20170304_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
