# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 05:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0005_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
