# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0006_auto_20170315_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='is_actibe',
            field=models.BooleanField(default=True),
        ),
    ]
