# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0008_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapapp.Bid'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapapp.Product'),
        ),
    ]
