# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0010_auto_20170319_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
