# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0012_auto_20170319_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ratings',
            field=models.IntegerField(default=5),
        ),
    ]
