# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0014_auto_20170321_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verify',
            field=models.CharField(default='', max_length=6),
        ),
    ]
