# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0015_auto_20170322_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ratings',
            field=models.IntegerField(null=True),
        ),
    ]
