# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0018_ads_is_bidded'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
