# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0019_contactus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='reply',
            field=models.CharField(default='', max_length=500),
        ),
    ]
