# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0021_transactions_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
