# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0023_transactions_bid_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='bid_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scrapapp.Bid_Detail'),
        ),
    ]
