# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 16:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0024_auto_20170328_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
