# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0025_ads_expires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expired_Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='ads',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 22, 26, 39, 3785)),
        ),
        migrations.AddField(
            model_name='expired_ad',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapapp.Ads'),
        ),
        migrations.AddField(
            model_name='expired_ad',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scrapapp.UserProfile'),
        ),
    ]
