# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 17:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0026_auto_20170329_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 22, 36, 49, 536080)),
        ),
    ]
