# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 04:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0029_auto_20170329_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapapp.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scrapapp.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='ads',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 11, 10, 0, 4, 954648)),
        ),
    ]
