# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-13 15:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0034_auto_20170404_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 20, 53, 58, 919076)),
        ),
    ]
