# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-13 15:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0035_auto_20170413_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 20, 56, 2, 363072)),
        ),
    ]
