# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0036_auto_20170413_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 22, 51, 6, 142144)),
        ),
    ]
